# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('create_time', models.DateTimeField()),
                ('last_change_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('pwdmethod', models.IntegerField(default=0)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('privileged', models.IntegerField(default=0)),
                ('invisible', models.IntegerField(default=0)),
                ('banned', models.IntegerField(default=0)),
                ('locked', models.IntegerField(default=0)),
                ('readonly', models.IntegerField(default=0)),
                ('neverclean', models.IntegerField(default=0)),
                ('simplereg', models.IntegerField(default=0)),
                ('regtime', models.DateTimeField(auto_now_add=True)),
                ('logintime', models.DateTimeField(auto_now_add=True)),
                ('pwdtime', models.DateTimeField(auto_now_add=True)),
                ('changetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logins',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('contest_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('createtime', models.DateTimeField()),
                ('changetime', models.DateTimeField()),
                ('firstname', models.CharField(blank=True, max_length=512, null=True)),
                ('firstname_en', models.CharField(blank=True, max_length=512, null=True)),
                ('middlename', models.CharField(blank=True, max_length=512, null=True)),
                ('middlename_en', models.CharField(blank=True, max_length=512, null=True)),
                ('surname', models.CharField(blank=True, max_length=512, null=True)),
                ('surname_en', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('grp', models.CharField(blank=True, max_length=512, null=True)),
                ('grp_en', models.CharField(blank=True, max_length=512, null=True)),
                ('occupation', models.CharField(blank=True, max_length=512, null=True)),
                ('occupation_en', models.CharField(blank=True, max_length=512, null=True)),
                ('discipline', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
                ('homepage', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, max_length=512, null=True)),
                ('inst', models.CharField(blank=True, max_length=512, null=True)),
                ('inst_en', models.CharField(blank=True, max_length=512, null=True)),
                ('instshort', models.CharField(blank=True, max_length=512, null=True)),
                ('instshort_en', models.CharField(blank=True, max_length=512, null=True)),
                ('fac', models.CharField(blank=True, max_length=512, null=True)),
                ('fac_en', models.CharField(blank=True, max_length=512, null=True)),
                ('facshort', models.CharField(blank=True, max_length=512, null=True)),
                ('facshort_en', models.CharField(blank=True, max_length=512, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Groupmembers',
            fields=[
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.Groups')),
                ('rights', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'groupmembers',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.Logins')),
                ('contest_id', models.IntegerField()),
                ('cnts_read_only', models.IntegerField()),
                ('instnum', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('pwdmethod', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('pwdtime', models.DateTimeField()),
                ('createtime', models.DateTimeField()),
                ('changetime', models.DateTimeField()),
                ('logintime', models.DateTimeField()),
                ('inst', models.CharField(blank=True, max_length=512, null=True)),
                ('inst_en', models.CharField(blank=True, max_length=512, null=True)),
                ('instshort', models.CharField(blank=True, max_length=512, null=True)),
                ('instshort_en', models.CharField(blank=True, max_length=512, null=True)),
                ('fac', models.CharField(blank=True, max_length=512, null=True)),
                ('fac_en', models.CharField(blank=True, max_length=512, null=True)),
                ('facshort', models.CharField(blank=True, max_length=512, null=True)),
                ('facshort_en', models.CharField(blank=True, max_length=512, null=True)),
                ('homepage', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=512, null=True)),
                ('city_en', models.CharField(blank=True, max_length=512, null=True)),
                ('region', models.CharField(blank=True, max_length=512, null=True)),
                ('area', models.CharField(blank=True, max_length=512, null=True)),
                ('zip', models.CharField(blank=True, max_length=512, null=True)),
                ('street', models.CharField(blank=True, max_length=512, null=True)),
                ('country', models.CharField(blank=True, max_length=512, null=True)),
                ('country_en', models.CharField(blank=True, max_length=512, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('spelling', models.CharField(blank=True, max_length=512, null=True)),
                ('printer', models.CharField(blank=True, max_length=512, null=True)),
                ('languages', models.CharField(blank=True, max_length=512, null=True)),
                ('exam_id', models.CharField(blank=True, max_length=512, null=True)),
                ('exam_cypher', models.CharField(blank=True, max_length=512, null=True)),
                ('field0', models.CharField(blank=True, max_length=512, null=True)),
                ('field1', models.CharField(blank=True, max_length=512, null=True)),
                ('field2', models.CharField(blank=True, max_length=512, null=True)),
                ('field3', models.CharField(blank=True, max_length=512, null=True)),
                ('field4', models.CharField(blank=True, max_length=512, null=True)),
                ('field5', models.CharField(blank=True, max_length=512, null=True)),
                ('field6', models.CharField(blank=True, max_length=512, null=True)),
                ('field7', models.CharField(blank=True, max_length=512, null=True)),
                ('field8', models.CharField(blank=True, max_length=512, null=True)),
                ('field9', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Logins'),
        ),
        migrations.AddField(
            model_name='groups',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Logins'),
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set([('user', 'contest_id')]),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Logins'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together=set([('group', 'user')]),
        ),
    ]
